### ISSUE TITLE
feature idea: Incorporate yarn into superpowers

### ISSUE THREAD

**Issue by blurymind** [superpowers/superpowers-core#119]
What is yarn:
https://github.com/InfiniteAmmoInc/Yarn

Dialogue editor created for "Night in the Woods" (and other projects) by @NoelFB and @infinite_ammo with contributions from @seiyria and @beeglebug. It is heavily inspired by and based on the amazing Twine software: http://twinery.org/

It can output a simple json file which can then be parsed as dialogue/logic in games - that is interactive.

Yarn is in html5, so it is possible to add it to superpowers and give it the superpower to be collaborative! 
try online: http://infiniteammo.com/yarn/

Having a yarn parser API in superpowers will make it easy to create adventure/rpg style games that rely heavily on story.
Currently there is a parser written in C#:
https://github.com/thesecretlab/YarnSpinner
it works on unity, since the games that yarn was used it run on unity. This is needed in order to be able to actually use yarn created dialogue/logic in your game.

So having Yarn in Superpowers will actually improve yarn in two ways:
- it will allow more than one user to simultaneously work on a Yarn file and together write their game's story.
- It will allow the developer to use yarn and yarn created dialogue without leaving the game engine - yarn editor being embedded in the game editor would allow that.

Having Yarn in superpowers would improve superpowers too:
- It will make it a more viable choice to make adventure style games in - as it will make it much easier to develop such type of games
- It could also potentially be used as a state machine - yarn's c# parser for example can take yarn json commands and parse them to trigger executing a function, changing a variable and all sorts of different things. Yarn dialogue boxes can also have a set of conditions in order to be triggered.
Paired with the interface of yarn editor - one can easily see it as a state machine editor, just as much as an interactive dialogue editor. Yarn syntax is very easy to understand:
https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/Usage.md

**Comment by elisee** [comment]
Hi and thanks for the suggestion!

I saw Yarn on Twitter a while ago, it looks rad! Sadly our hands are more than full, there is an infinite number of plugins that @bilou84  and I would want to build or improve, and only so much time ^_^. That's why our focus is on improving Superpowers itself so that people who want to use particular engines, frameworks or libraries can expose them themselves. We must remove ourselves as a bottleneck and let the community shine!

Currently we're focusing on the redesigned Superpowers app (v1.0) with support for auto-updates for the core, systems and plugins. After v1.0 is out, we're going to work to make it easy to find and install plugins, and write more documentation for system / plugin authors, with the goal of creating a large ecosystem of community-maintained plugins. Hopefully this will allow libraries like Yarn to be integrated by the community.
