### ISSUE TITLE
"Error: The system game is not installed." <-- add howto fix hint

### ISSUE THREAD

**Issue by mk-pmb** [superpowers/superpowers-core#123]
Could you extend this error message to show the suggested next steps to investigate or fix it? A URL to the FAQ or an issue thread might suffice.

```text
The server crashed while loading project "pac-man-like-game".
Error: The system game is not installed.
    at done (/…/sp-dev/core/server/ProjectServer.js:122:30)
    at /…/sp-dev/core/server/ProjectServer.js:149:17
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

```text
Devel environment: Node.js v5.7.1, npm v3.6.0, Ubuntu 12.04.5 LTS precise
sp-dev/app = superpowers/superpowers-app @ d0af9ed: Make travis notify gitter
sp-dev/core = superpowers/superpowers-core @ 2f266e9: SupClient: Store client ID on ProjectClient
sp-dev/core/systems/game = superpowers/superpowers-game @ d1ce643: scene: Allow dropping scene in a prefab again. Fixes #79
sp-dev/proj/pac-man-like-game = superpowers-extra/pac-man-like-game @ 89c10e0: Create README.md
```

__Update:__ Another worthy hint would be which expectation failed, e.g.

> Unable to read ~/.local/share/Superpowers/systems/game/package.json

By chance I noticed that there's an empty directory `~/.local/share/Superpowers/systems/`, so in there I symlinked the `game` directory from `~/.local/share/Superpowers/core/systems/` (note the inserted `core/`):
```bash
cd sp-dev/home/.local/share/Superpowers/systems
ln --symbolic --target-directory=. ../core/systems/game
```

And now the server successfully starts.

**Comment by elisee** [comment]
Thanks for the report. We're getting pretty close to finishing the new version of the app and the location from which systems are loaded has changed to make auto-updates possible.

Not too sure why you had to create a symlink but we'll make sure to double-check that before shipping v1.0.  Leaving this issue open until then.

**Comment by mk-pmb** [comment]
Thanks! There could be better solutions than a symlink, so my core issue is to have any guidepost in the error message. :+1:

**Comment by elisee** [comment]
OK reopening. This is where the error message is: https://github.com/superpowers/superpowers-core/blob/9409a2368a3a2f078248075831ecf6b5b33d4edd/server/ProjectServer.ts#L52

I guess it should say `Run "node server install ${this.data.manifest.pub.systemId}" to install it.`?

**Comment by mk-pmb** [comment]
Can't verify the command from here but sounds good. :-)

**Comment by elisee** [comment]
> Can't verify the command from here but sounds good. :-)

Ok, will do, unless someone does a PR for it before I can get to it :P

> PS: What's the benefit of if (this.system == null) { over just if (!this.system) {?

It's more explicit about what we want to test. We want to know whether `this.system` is null (or undefined), not if it is "falsy", which could mean any one of those values: `false`, `0`, `""`, `NaN`, etc.

Both would work in that case, since it's unlikely that `this.system` would ever contain those other values. But it's nice to be explicit about our expectations.

**Comment by mk-pmb** [comment]
Thanks for the explanation. Sounds like you can instandly reliably remember the double-equal conversion rules, probably that's quite handy. I'd have to stop and think when I see constructs like that, so I tend to avoid them where I can.

**Comment by elisee** [comment]
We use `===` everywhere (no conversion) except for checking against `null`, because we want to check for both `null` and `undefined`. That's the only rule we have to remember in Superpowers's codebase.

In my opinion, that's much simpler than using `!` on non-boolean values and having to wonder if the value could be any of the many falsy values, which could introduce subtle bugs. Like, if a value is an empty string, checking with `!` would lead to a bug if you actually wanted to check if it was null.
