### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [superpowers/superpowers-core#143]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _superpowers-core_, deleted their software history when transitioning to open-source.

https://github.com/superpowers/superpowers-core/commit/027ed12b46e6eb8bcc3cf1464ddbe9c8e914f540

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask superpowers-core developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by elisee** [comment]
Hi Gustavo,

> 1. Why did you decide to not keep the software history?

I went digging into some of our [old livestream archives (in French)](https://youtu.be/Oh-S6StQIAg?t=464), because I couldn't quite remember. Here's what happened:

Back in February 2015, we split the core of Superpowers and the "Superpowers Game" system into separate repositories and made the whole project more modular. Instead of a single build script that generated huge JS bundles, the core and the plugins were made compilable separately, reducing build times for plugin development and allowing plugins to hook into the engine rather than been compiled into it.

So the loss of history isn't related to going open source but it happened because of a major refactoring of the codebase. We only started sharing the code in a semi-open fashion a couple months (early access w/ source code access for supporters), and went fully open (which was the plan from the start) in January 2016 IIRC.

> 2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?

I believe what happened is that initially we kept around the old repository for a while, so we had something like `superpowers` (the deprecated monolithic version) and `superpowers-core` (active) and `superpowers-game` (active).

At some point (probably a few months later) we just deleted the old `superpowers` repository since it wasn't relevant and we didn't want to clutter the list of repositories. I probably have an old copy lying around on my old computer, but the need to dig it up hasn't come up.

> 3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
> 4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

I don't think it's been a hindrance for anyone. The imported `superpowers-core` in the initial commit is actually pretty small / manageable, and I don't think the old repo history would have much value for further development since the new repository came with a fairly major refactoring.

Hope that's helpful!

**Comment by gustavopinto** [comment]
Hi @elisee, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
