### ISSUE TITLE
Move recursive asset folder deletion to server so that it's more robust

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-core#95]
Currently it is done client-side by looping over entries and it doesn't work great.

**Comment by chrisbubernak** [comment]
@elisee I was looking into this but was a bit confused because it looks like asset deletion is already done recursively on the server. Doing a little digging I think it was fixed with [this commit](https://github.com/superpowers/superpowers-core/commit/3d2803866b8841e7311efbcf2d13474cf6c80628).

Is there something I'm missing here?

**Comment by elisee** [comment]
Looks like it is indeed. Closing!
